export const maxPostBoxSize = 5;
export const maxSiblingTownNum = 5;
export const smallestTownSize = 15;
export const maxTownSizeRatio = 0.6;
export const minTownSizeRatio = 0.3;
export const maxTownMarginRatio = (1 - maxTownSizeRatio) / 8;
export const minTownMarginRatio = 0;
export const postBoxExistingProbability = 0.2;
export const highlightTownCssPath = "./highlightTown.css";
